-- 1.DISPLAY ALL CUSTOMERS
SELECT
    CUSTOMER_NAME
FROM CUSTOMERS;

-- 2.DISPLAY ALL UNIQUE CUSTOMER CITIES
SELECT
    DISTINCT CITY
FROM CUSTOMERS;

-- 3.FIND ALL PRODUCTS BELONGING TO THE ELECTRONICS CATEGORY
SELECT
    DISTINCT PRODUCT_NAME
FROM PRODUCTS
WHERE CATEGORY = "ELECTRONICS";

-- 4.FIND PRODUCTS WITH A PRICE GREATER THAN ₹50,000
SELECT
    DISTINCT PRODUCT_NAME,
    PRICE
FROM PRODUCTS
WHERE PRICE > 50000;

-- 5.FIND ORDERS PLACED IN MARCH 2026
SELECT *
FROM ORDERS
WHERE ORDER_DATE
    BETWEEN "2026-03-01" AND "2026-03-31";

-- 6.DISPLAY THE 10 MOST EXPENSIVE PRODUCTS
SELECT
    PRODUCT_NAME,
    PRICE
FROM PRODUCTS
ORDER BY PRICE DESC
LIMIT 10;

-- 7.FIND ORDERS PAID USING UPI OR CREDIT CARD
SELECT *
FROM ORDERS
WHERE PAYMENT_METHOD IN ("UPI","CREDIT CARD");

-- 8.COUNT THE TOTAL NUMBER OF CUSTOMERS
SELECT
    COUNT(*) AS CUSTOMER_COUNT
FROM CUSTOMERS;

-- 9.COUNT THE TOTAL NUMBER OF ORDERS
SELECT
    COUNT(*) AS ORDER_COUNT
FROM ORDERS;

-- 10.CALCULATE TOTAL REVENUE AND TOTAL PROFIT
SELECT
    SUM(SALES_AMOUNT) AS TOTAL_REVENUE,
    SUM(PROFIT) AS TOTAL_PROFIT
FROM ORDER_DETAILS;

-- 11.FIND TOTAL SALES BY CATEGORY
SELECT
    P.CATEGORY,
    SUM(O.SALES_AMOUNT) AS TOTAL_SALES
FROM ORDER_DETAILS AS O
INNER JOIN PRODUCTS AS P
    ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.CATEGORY;

-- 12.FIND TOTAL PROFIT BY CATEGORY
SELECT
    P.CATEGORY,
    SUM(O.PROFIT) AS TOTAL_PROFIT
FROM ORDER_DETAILS AS O
INNER JOIN PRODUCTS AS P
    ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.CATEGORY;

-- 13.FIND THE NUMBER OF ORDERS HANDLED BY EACH SALES REPRESENTATIVE
SELECT
    S.SALES_REP_ID,
    S.SALES_REP_NAME,
    COUNT(O.ORDER_ID) AS ORDER_COUNT
FROM ORDERS AS O
INNER JOIN SALES_REPS AS S
    ON O.SALES_REP_ID = S.SALES_REP_ID
GROUP BY S.SALES_REP_ID, S.SALES_REP_NAME;

-- 14.FIND THE TOP 10 CUSTOMERS BY REVENUE
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(OD.SALES_AMOUNT) AS TOTAL_REVENUE
FROM CUSTOMERS AS C
INNER JOIN ORDERS AS O
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
INNER JOIN ORDER_DETAILS AS OD
    ON OD.ORDER_ID = O.ORDER_ID
GROUP BY C.CUSTOMER_ID, C.CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

-- 15.FIND THE TOP 10 PRODUCTS BY REVENUE
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(OD.SALES_AMOUNT) AS TOTAL_REVENUE
FROM PRODUCTS AS P
INNER JOIN ORDER_DETAILS AS OD
    ON P.PRODUCT_ID = OD.PRODUCT_ID
GROUP BY PRODUCT_ID,PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

-- 16.FIND THE TOP 5 PRODUCTS BY PROFIT
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(OD.PROFIT) AS TOTAL_PROFIT
FROM PRODUCTS AS P
INNER JOIN ORDER_DETAILS AS OD
    ON P.PRODUCT_ID = OD.PRODUCT_ID
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY TOTAL_PROFIT DESC
LIMIT 5;

-- 17.FIND TOTAL SALES BY CITY
SELECT
    C.CITY,
    SUM(OD.SALES_AMOUNT) AS TOTAL_SALES
FROM CUSTOMERS AS C
INNER JOIN ORDERS AS O
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
INNER JOIN ORDER_DETAILS AS OD
    ON OD.ORDER_ID = O.ORDER_ID
GROUP BY C.CITY;

-- 18.FIND THE CITY WITH THE HIGHEST REVENUE
SELECT
    C.CITY,
    SUM(OD.SALES_AMOUNT) AS TOTAL_REVENUE
FROM CUSTOMERS AS C
INNER JOIN ORDERS AS O
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
INNER JOIN ORDER_DETAILS AS OD
    ON OD.ORDER_ID = O.ORDER_ID
GROUP BY CITY
ORDER BY TOTAL_REVENUE DESC
LIMIT 1;

-- 19.CALCULATE AVERAGE ORDER VALUE
SELECT
    SUM(SALES_AMOUNT) / COUNT(DISTINCT ORDER_ID) AS AVERAGE_ORDER_VALUE
FROM ORDER_DETAILS;

-- 20.FIND MONTHS WITH TOTAL REVENUE GREATER THAN ₹1,000,000
SELECT
    YEAR(O.ORDER_DATE) AS ORDER_YEAR,
    MONTHNAME(O.ORDER_DATE) AS MONTH_NAME,
    SUM(OD.SALES_AMOUNT) AS TOTAL_REVENUE
FROM ORDERS AS O
INNER JOIN ORDER_DETAILS AS OD
    ON O.ORDER_ID = OD.ORDER_ID
GROUP BY YEAR(O.ORDER_DATE),MONTHNAME(O.ORDER_DATE)
HAVING SUM(OD.SALES_AMOUNT) > 1000000;

-- 21.DISPLAY ORDER ID, ORDER DATE, CUSTOMER NAME, PRODUCT NAME, QUANTITY AND SALES AMOUNT
SELECT
    OD.ORDER_ID,
    O.ORDER_DATE,
    C.CUSTOMER_NAME,
    P.PRODUCT_NAME,
    OD.QUANTITY,
    OD.SALES_AMOUNT
FROM ORDER_DETAILS AS OD
INNER JOIN ORDERS AS O
    ON O.ORDER_ID = OD.ORDER_ID
INNER JOIN CUSTOMERS AS C
    ON O.CUSTOMER_ID = C.CUSTOMER_ID
INNER JOIN PRODUCTS AS P
    ON OD.PRODUCT_ID = P.PRODUCT_ID;

-- 22.FIND CUSTOMERS WHO HAVE PLACED MORE THAN 5 ORDERS
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    COUNT(O.ORDER_ID) AS ORDER_COUNT
FROM ORDERS AS O
INNER JOIN CUSTOMERS AS C
    ON O.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID, C.CUSTOMER_NAME
HAVING COUNT(O.ORDER_ID) > 5;

-- 23.FIND PRODUCTS WHOSE SALES ARE ABOVE THE AVERAGE PRODUCT SALES
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(OD.SALES_AMOUNT) AS TOTAL_PRODUCT_REVENUE
FROM PRODUCTS AS P
INNER JOIN ORDER_DETAILS AS OD
    ON P.PRODUCT_ID = OD.PRODUCT_ID
GROUP BY PRODUCT_ID,PRODUCT_NAME
HAVING TOTAL_PRODUCT_REVENUE > (
    SELECT AVG(AVG_PRODUCT)
    FROM (
        SELECT PRODUCT_ID,
            SUM(SALES_AMOUNT) AS AVG_PRODUCT
        FROM ORDER_DETAILS
        GROUP BY PRODUCT_ID) AS T);

-- 24.FIND CUSTOMERS WHOSE TOTAL SPENDING IS ABOVE AVERAGE CUSTOMER SPENDING
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(OD.SALES_AMOUNT) AS TOTAL_CUSTOMER_SPENDING
FROM CUSTOMERS AS C
INNER JOIN ORDERS AS O
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
INNER JOIN ORDER_DETAILS AS OD
    ON O.ORDER_ID = OD.ORDER_ID
GROUP BY C.CUSTOMER_ID, C.CUSTOMER_NAME
HAVING TOTAL_CUSTOMER_SPENDING > (
    SELECT AVG(CUSTOMER_SPENDING)
    FROM (
        SELECT
            O.CUSTOMER_ID,
            SUM(OD.SALES_AMOUNT) AS CUSTOMER_SPENDING
        FROM ORDERS AS O
        INNER JOIN ORDER_DETAILS AS OD
            ON O.ORDER_ID = OD.ORDER_ID
        GROUP BY O.CUSTOMER_ID) AS T);

-- 25.FIND THE HIGHEST-SELLING PRODUCT IN EACH CATEGORY
WITH PRODUCT_SALES AS (
    SELECT
        P.PRODUCT_ID,
        P.PRODUCT_NAME,
        P.CATEGORY,
        SUM(OD.SALES_AMOUNT) AS TOTAL_SALES
    FROM PRODUCTS AS P
    INNER JOIN ORDER_DETAILS AS OD
        ON P.PRODUCT_ID = OD.PRODUCT_ID
    GROUP BY
        P.PRODUCT_ID,
        P.PRODUCT_NAME,
        P.CATEGORY )
SELECT
    PRODUCT_NAME,
    CATEGORY,
    TOTAL_SALES
FROM PRODUCT_SALES AS PS
WHERE TOTAL_SALES = (
    SELECT
        MAX(TOTAL_SALES)
    FROM PRODUCT_SALES AS PS2
    WHERE PS2.CATEGORY = PS.CATEGORY);

-- 26.FIND SALES REPRESENTATIVES WHOSE REVENUE IS ABOVE AVERAGE SALES-REPRESENTATIVE REVENUE
SELECT
    S.SALES_REP_ID,
    S.SALES_REP_NAME,
    SUM(OD.SALES_AMOUNT) AS REVENUE_OF_SALES_REP
FROM SALES_REPS AS S
INNER JOIN ORDERS AS O
    ON S.SALES_REP_ID = O.SALES_REP_ID
INNER JOIN ORDER_DETAILS AS OD
    ON O.ORDER_ID = OD.ORDER_ID
GROUP BY S.SALES_REP_ID,S.SALES_REP_NAME
HAVING SUM(OD.SALES_AMOUNT) > (
    SELECT
        AVG(SALES_REP_REVENUE)
    FROM (
        SELECT
            O.SALES_REP_ID,
            SUM(OD.SALES_AMOUNT) AS SALES_REP_REVENUE
        FROM ORDERS AS O
        INNER JOIN ORDER_DETAILS AS OD
            ON O.ORDER_ID = OD.ORDER_ID
        GROUP BY
            O.SALES_REP_ID) AS T);

-- 27.USING A CTE, CALCULATE TOTAL REVENUE PER CUSTOMER AND RETURN CUSTOMERS WHOSE REVENUE IS ABOVE AVERAGE CUSTOMER REVENUE
WITH TOTAL_REVENUE_OF_CUSTOMER AS (
    SELECT
        C.CUSTOMER_NAME,
        SUM(OD.SALES_AMOUNT) AS TOTAL_REVENUE
    FROM CUSTOMERS AS C
    INNER JOIN ORDERS AS O
        ON C.CUSTOMER_ID = O.CUSTOMER_ID
    INNER JOIN ORDER_DETAILS AS OD
        ON O.ORDER_ID = OD.ORDER_ID
    GROUP BY
        C.CUSTOMER_ID,
        C.CUSTOMER_NAME)
SELECT *
FROM TOTAL_REVENUE_OF_CUSTOMER
WHERE TOTAL_REVENUE > (
    SELECT
        AVG(TOTAL_REVENUE)
    FROM TOTAL_REVENUE_OF_CUSTOMER);

-- 28.USING A CTE, CALCULATE MONTHLY SALES AND IDENTIFY THE BEST-PERFORMING MONTH
WITH MONTHLY_SALES AS (
    SELECT
        MONTHNAME(O.ORDER_DATE) AS MONTH_NAME,
        SUM(OD.SALES_AMOUNT) AS TOTAL_AMOUNT
    FROM ORDERS AS O
    INNER JOIN ORDER_DETAILS AS OD
        ON O.ORDER_ID = OD.ORDER_ID
    GROUP BY MONTHNAME(O.ORDER_DATE))
SELECT *
FROM MONTHLY_SALES
WHERE TOTAL_AMOUNT = (
    SELECT
        MAX(TOTAL_AMOUNT)
    FROM MONTHLY_SALES);

-- 29.USING A CTE, CALCULATE CATEGORY REVENUE AND PROFIT MARGIN, THEN IDENTIFY THE CATEGORY WITH THE HIGHEST PROFIT MARGIN
WITH PROFIT_MARGIN AS (
    SELECT
        P.CATEGORY,
        SUM(OD.SALES_AMOUNT) AS CATEGORY_REVENUE,
        (SUM(OD.PROFIT ) / SUM(OD.SALES_AMOUNT) ) * 100 AS PROFIT_MARGIN
    FROM PRODUCTS AS P
    INNER JOIN ORDER_DETAILS AS OD
        ON P.PRODUCT_ID = OD.PRODUCT_ID
    GROUP BY  P.CATEGORY)
SELECT *
FROM PROFIT_MARGIN
WHERE PROFIT_MARGIN = (
    SELECT
        MAX(PROFIT_MARGIN)
    FROM
        PROFIT_MARGIN);

-- 30.RANK PRODUCTS BY REVENUE
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(OD.SALES_AMOUNT) AS TOTAL_PRODUCT_REVENUE,
    DENSE_RANK() OVER(ORDER BY SUM(OD.SALES_AMOUNT) DESC) AS PRODUCT_RANK
FROM PRODUCTS AS P
INNER JOIN ORDER_DETAILS AS OD
    ON P.PRODUCT_ID = OD.PRODUCT_ID
GROUP BY P.PRODUCT_ID,P.PRODUCT_NAME;

-- 31.RANK PRODUCTS WITHIN EACH CATEGORY BY REVENUE
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY,
    SUM(OD.SALES_AMOUNT) AS TOTAL_PRODUCT_REVENUE,
    DENSE_RANK() OVER(PARTITION BY P.CATEGORY ORDER BY SUM(OD.SALES_AMOUNT) DESC) AS PRODUCT_RANK
FROM PRODUCTS AS P
INNER JOIN ORDER_DETAILS AS OD
    ON P.PRODUCT_ID = OD.PRODUCT_ID
GROUP BY P.PRODUCT_ID,P.PRODUCT_NAME,P.CATEGORY;

-- 32.FIND THE TOP 3 PRODUCTS IN EVERY CATEGORY
WITH TOP_RANK_3_PRODUCT_WITH_IN_CATEGORY AS (
    SELECT
        P.PRODUCT_ID,
        P.PRODUCT_NAME,
        P.CATEGORY,
        SUM(OD.SALES_AMOUNT),
        DENSE_RANK() OVER(PARTITION BY P.CATEGORY ORDER BY SUM(OD.SALES_AMOUNT)DESC) AS PRODUCT_RANK
    FROM PRODUCTS AS P
    INNER JOIN ORDER_DETAILS AS OD
        ON P.PRODUCT_ID = OD.PRODUCT_ID
    GROUP BY P.PRODUCT_ID,P.PRODUCT_NAME,P.CATEGORY)
SELECT *
FROM TOP_RANK_3_PRODUCT_WITH_IN_CATEGORY
WHERE
    PRODUCT_RANK IN (1,2,3);

-- 33.CALCULATE MONTHLY REVENUE AND PREVIOUS-MONTH REVENUE USING LAG()
SELECT
    MONTHNAME(O.ORDER_DATE) AS MONTH_NAME,
    SUM(OD.SALES_AMOUNT) AS MONTHLY_SALES_AMOUNT,
    LAG( SUM(OD.SALES_AMOUNT) ) OVER(ORDER BY MONTH(O.ORDER_DATE)) AS PREVIOUS_MONTH_SALES_AMOUNT
FROM ORDERS AS O
INNER JOIN ORDER_DETAILS AS OD
    ON O.ORDER_ID = OD.ORDER_ID
GROUP BY MONTH(O.ORDER_DATE), MONTHNAME(O.ORDER_DATE);

-- 34.CALCULATE MONTH-OVER-MONTH REVENUE GROWTH PERCENTAGE
WITH MONTHLY_REVENUE AS (
    SELECT
        MONTH(O.ORDER_DATE) AS MONTH_NUMBER,
        MONTHNAME(O.ORDER_DATE) AS MONTH_NAME,
        SUM(OD.SALES_AMOUNT) AS CURRENT_MONTH_SALES_AMOUNT
    FROM
        ORDERS AS O
    INNER JOIN ORDER_DETAILS AS OD
        ON O.ORDER_ID = OD.ORDER_ID
    GROUP BY MONTH(O.ORDER_DATE), MONTHNAME(O.ORDER_DATE))
SELECT
    MONTH_NAME,
    CURRENT_MONTH_SALES_AMOUNT,
    LAG(CURRENT_MONTH_SALES_AMOUNT) OVER(ORDER BY MONTH_NUMBER) AS PREVIOUS_MONTH_SALES_AMOUNT,
    (
            ( CURRENT_MONTH_SALES_AMOUNT - LAG(CURRENT_MONTH_SALES_AMOUNT) OVER(ORDER BY MONTH_NUMBER) ) / (LAG(CURRENT_MONTH_SALES_AMOUNT) OVER(ORDER BY MONTH_NUMBER))
    ) * 100 AS MOM_GROWTH
FROM MONTHLY_REVENUE
GROUP BY MONTH_NUMBER,MONTH_NAME;

-- 35.CALCULATE CUMULATIVE REVENUE BY MONTH
SELECT
    MONTHNAME(O.ORDER_DATE) AS MONTH_NAME,
    SUM(OD.SALES_AMOUNT) AS MONTHLY_REVENUE,
    SUM(SUM(OD.SALES_AMOUNT)) OVER(ORDER BY MONTH(O.ORDER_DATE)) AS CUMULATIVE_REVENUE
FROM ORDERS AS O
INNER JOIN ORDER_DETAILS AS OD
    ON O.ORDER_ID = OD.ORDER_ID
GROUP BY MONTH(O.ORDER_DATE), MONTHNAME(O.ORDER_DATE)
ORDER BY MONTH(O.ORDER_DATE);

-- 36.ASSIGN CUSTOMERS TO REVENUE RANKS BASED ON TOTAL SPENDING
SELECT
    C.CUSTOMER_NAME,
    SUM(OD.SALES_AMOUNT) AS TOTAL_REVENUE,
    DENSE_RANK() OVER(ORDER BY SUM(OD.SALES_AMOUNT) DESC) AS CUSTOMER_RANK
FROM CUSTOMERS AS C
INNER JOIN ORDERS AS O
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
INNER JOIN ORDER_DETAILS AS OD
    ON O.ORDER_ID = OD.ORDER_ID
GROUP BY C.CUSTOMER_ID, C.CUSTOMER_NAME;

-- 37.IDENTIFY CUSTOMERS WHO PLACED ORDERS IN JANUARY BUT NOT IN FEBRUARY
WITH ORDERS_PLACED AS (
    SELECT
        C.CUSTOMER_ID,
        C.CUSTOMER_NAME,
        MONTHNAME(O.ORDER_DATE) AS MONTH_NAME
    FROM CUSTOMERS AS C
    INNER JOIN ORDERS AS O
        ON C.CUSTOMER_ID = O.CUSTOMER_ID
    GROUP BY
        C.CUSTOMER_NAME,
        C.CUSTOMER_ID,
        MONTHNAME(O.ORDER_DATE)
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    MONTH_NAME
FROM ORDERS_PLACED
WHERE MONTH_NAME = "JANUARY"
  AND CUSTOMER_ID NOT IN (
      SELECT CUSTOMER_ID
      FROM ORDERS_PLACED
      WHERE MONTH_NAME = "FEBRUARY"
  );

-- 38.FIND THE PERCENTAGE CONTRIBUTION OF EACH CATEGORY TO TOTAL REVENUE
SELECT
    P.CATEGORY,
    SUM(OD.SALES_AMOUNT) AS CATEGORY_REVENUE,
    SUM(OD.SALES_AMOUNT) * 100 / SUM(SUM(OD.SALES_AMOUNT)) OVER() AS REVENUE_PERCENTAGE
FROM PRODUCTS AS P
INNER JOIN ORDER_DETAILS AS OD
    ON P.PRODUCT_ID = OD.PRODUCT_ID
GROUP BY P.CATEGORY;

-- 39.FIND EACH SALES REPRESENTATIVE'S PERCENTAGE CONTRIBUTION TO TOTAL COMPANY REVENUE
SELECT
    S.SALES_REP_ID,
    S.SALES_REP_NAME,
    SUM(OD.SALES_AMOUNT) * 100 / SUM(SUM(OD.SALES_AMOUNT))OVER () AS SALES_REP_PERCENTAGE
FROM SALES_REPS AS S
INNER JOIN ORDERS AS O
    ON S.SALES_REP_ID = O.SALES_REP_ID
INNER JOIN ORDER_DETAILS AS OD
    ON O.ORDER_ID = OD.ORDER_ID
GROUP BY S.SALES_REP_ID, S.SALES_REP_NAME;

-- 40.IDENTIFY THE MONTH WITH THE HIGHEST REVENUE GROWTH
WITH REVENUE_GROWTH AS (
    SELECT
        MONTH(O.ORDER_DATE) AS MONTH_NUMBER,
        MONTHNAME(O.ORDER_DATE) AS MONTH_NAME,
        SUM(OD.SALES_AMOUNT) AS CURRENT_MONTH_REVENUE,
        LAG(SUM(OD.SALES_AMOUNT)) OVER(ORDER BY MONTH(O.ORDER_DATE)) AS PREVIOUS_MONTH_REVENUE
    FROM ORDERS AS O
    INNER JOIN ORDER_DETAILS AS OD
        ON O.ORDER_ID = OD.ORDER_ID
    GROUP BY MONTH(O.ORDER_DATE), MONTHNAME(O.ORDER_DATE))
SELECT
    MONTH_NAME,
    CURRENT_MONTH_REVENUE,
    PREVIOUS_MONTH_REVENUE,
    (
            (CURRENT_MONTH_REVENUE - PREVIOUS_MONTH_REVENUE ) / PREVIOUS_MONTH_REVENUE) * 100 AS REVENUE_GROWTH
FROM
    REVENUE_GROWTH
WHERE (
        (CURRENT_MONTH_REVENUE - PREVIOUS_MONTH_REVENUE ) / PREVIOUS_MONTH_REVENUE) * 100 = (
    SELECT
        MAX(
                ((CURRENT_MONTH_REVENUE - PREVIOUS_MONTH_REVENUE ) / PREVIOUS_MONTH_REVENUE) * 100
        )
    FROM REVENUE_GROWTH);

-- 41.FIND PRODUCTS WITH HIGH REVENUE BUT LOW PROFIT MARGIN
WITH PRODUCT_MARGIN AS (
    SELECT
        P.PRODUCT_ID,
        P.PRODUCT_NAME,
        SUM(OD.SALES_AMOUNT) AS TOTAL_REVENUE,
        SUM(OD.PROFIT) AS TOTAL_PROFIT,
        SUM(OD.PROFIT) * 100 / SUM(OD.SALES_AMOUNT) AS PROFIT_MARGIN
    FROM PRODUCTS AS P
    INNER JOIN ORDER_DETAILS AS OD
        ON P.PRODUCT_ID = OD.PRODUCT_ID
    GROUP BY PRODUCT_ID,PRODUCT_NAME)
SELECT
    PRODUCT_NAME,
    TOTAL_REVENUE,
    PROFIT_MARGIN
FROM PRODUCT_MARGIN
WHERE TOTAL_REVENUE > (
    SELECT
        AVG(TOTAL_REVENUE)
    FROM PRODUCT_MARGIN
)
AND
    PROFIT_MARGIN < (
        SELECT
            AVG(PROFIT_MARGIN)
        FROM PRODUCT_MARGIN);

-- 42.IDENTIFY THE TOP 20% OF CUSTOMERS BY REVENUE
WITH CUSTOMERS_REVENUE AS (
    SELECT
        C.CUSTOMER_ID,
        C.CUSTOMER_NAME,
        SUM(OD.SALES_AMOUNT) AS TOTAL_REVENUE
    FROM CUSTOMERS AS C
    INNER JOIN ORDERS AS O
        ON C.CUSTOMER_ID = O.CUSTOMER_ID
    INNER JOIN ORDER_DETAILS AS OD
        ON O.ORDER_ID = OD.ORDER_ID
    GROUP BY C.CUSTOMER_ID, C.CUSTOMER_NAME),
    RANKED_CUSTOMER AS (
        SELECT
            CUSTOMER_ID,
            CUSTOMER_NAME,
            TOTAL_REVENUE,
            ROW_NUMBER() OVER(ORDER BY TOTAL_REVENUE DESC) AS RN,
            COUNT(*) OVER () AS TOTAL_CUSTOMER_COUNT
        FROM CUSTOMERS_REVENUE)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    TOTAL_REVENUE
FROM RANKED_CUSTOMER
WHERE RN <= CEIL(TOTAL_CUSTOMER_COUNT * 0.20)
ORDER BY TOTAL_REVENUE DESC;

-- 43.FIND THE BEST-PERFORMING CITY FOR EACH PRODUCT CATEGORY
WITH CITY_REVENUE AS (
    SELECT
        C.CITY,
        P.CATEGORY,
        SUM(OD.SALES_AMOUNT) AS REVENUE
    FROM CUSTOMERS AS C
    INNER JOIN ORDERS AS O
        ON C.CUSTOMER_ID = O.CUSTOMER_ID
    INNER JOIN ORDER_DETAILS AS OD
        ON O.ORDER_ID = OD.ORDER_ID
    INNER JOIN PRODUCTS AS P
        ON OD.PRODUCT_ID = P.PRODUCT_ID
    GROUP BY C.CITY, P.CATEGORY),
    RANKED_CITY AS (
        SELECT
            CITY,
            CATEGORY,
            REVENUE,
            ROW_NUMBER() OVER(PARTITION BY CATEGORY ORDER BY REVENUE DESC) AS RN
        FROM CITY_REVENUE)
SELECT
    CITY,
    CATEGORY,
    REVENUE
FROM RANKED_CITY
WHERE RN = 1;

-- 44.FIND EACH CUSTOMER'S FIRST ORDER DATE AND LATEST ORDER DATE
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    MIN(O.ORDER_DATE) AS FIRST_ORDER_DAY,
    MAX(O.ORDER_DATE) AS LATEST_ORDER_DATE
FROM CUSTOMERS AS C
INNER JOIN ORDERS AS O
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID, C.CUSTOMER_NAME;

-- 45.IDENTIFY CUSTOMERS WHO HAVE NOT PURCHASED IN THE LAST 60 DAYS OF THE DATASET
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    MAX(O.ORDER_DATE) AS LATEST_ORDER_DATE
FROM CUSTOMERS AS C
INNER JOIN ORDERS AS O
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID, C.CUSTOMER_NAME
HAVING MAX(O.ORDER_DATE) < (
    SELECT MAX(ORDER_DATE)
    FROM ORDERS
) - INTERVAL 60 DAY;



























